import { ProjectItem, ProjectSeo } from '../types';

/**
 * Injects or updates SEO, OpenGraph, and Twitter social cards into an HTML string.
 */
export function injectSeoMetadata(
  rawHtml: string,
  project: Pick<ProjectItem, 'title' | 'description' | 'seo' | 'slug' | 'publishedUrl'>,
  fallbackOrigin?: string
): string {
  if (!rawHtml) return '';

  const seo: ProjectSeo = project.seo || {};
  const pageTitle = seo.title?.trim() || project.title?.trim() || 'موقع سَوّيها';
  const metaDesc = seo.description?.trim() || project.description?.trim() || 'موقع أُنشئ وطُوّر عبر منصة سَوّيها للذكاء الاصطناعي';
  const keywords = seo.keywords?.trim() || '';
  const ogTitle = seo.ogTitle?.trim() || pageTitle;
  const ogDesc = seo.ogDescription?.trim() || metaDesc;
  const ogImage = seo.ogImage?.trim() || '';
  const favicon = seo.favicon?.trim() || '';
  const canonical = seo.canonicalUrl?.trim() || project.publishedUrl || (fallbackOrigin && project.slug ? `${fallbackOrigin}/s/${project.slug}` : '');

  // Escape HTML attribute special characters
  const escapeAttr = (str: string) =>
    str.replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const cleanTitle = escapeAttr(pageTitle);
  const cleanDesc = escapeAttr(metaDesc);
  const cleanKeywords = escapeAttr(keywords);
  const cleanOgTitle = escapeAttr(ogTitle);
  const cleanOgDesc = escapeAttr(ogDesc);

  let tagsToInsert = `
  <!-- Primary SEO Meta Tags -->
  <title>${cleanTitle}</title>
  <meta name="title" content="${cleanTitle}">
  <meta name="description" content="${cleanDesc}">
`;

  if (cleanKeywords) {
    tagsToInsert += `  <meta name="keywords" content="${cleanKeywords}">\n`;
  }
  if (seo.author) {
    tagsToInsert += `  <meta name="author" content="${escapeAttr(seo.author)}">\n`;
  }
  if (canonical) {
    tagsToInsert += `  <link rel="canonical" href="${escapeAttr(canonical)}">\n`;
  }
  if (favicon) {
    tagsToInsert += `  <link rel="icon" href="${escapeAttr(favicon)}">\n`;
  }

  // Open Graph / Facebook
  tagsToInsert += `
  <!-- Open Graph / Facebook / WhatsApp -->
  <meta property="og:type" content="website">
  <meta property="og:title" content="${cleanOgTitle}">
  <meta property="og:description" content="${cleanOgDesc}">
`;
  if (canonical) {
    tagsToInsert += `  <meta property="og:url" content="${escapeAttr(canonical)}">\n`;
  }
  if (ogImage) {
    tagsToInsert += `  <meta property="og:image" content="${escapeAttr(ogImage)}">\n`;
  }

  // Twitter Card
  tagsToInsert += `
  <!-- Twitter Cards -->
  <meta name="twitter:card" content="${ogImage ? 'summary_large_image' : 'summary'}">
  <meta name="twitter:title" content="${cleanOgTitle}">
  <meta name="twitter:description" content="${cleanOgDesc}">
`;
  if (ogImage) {
    tagsToInsert += `  <meta name="twitter:image" content="${escapeAttr(ogImage)}">\n`;
  }

  // If the document has a <head> tag, strip previous generic title/meta description and insert
  if (rawHtml.toLowerCase().includes('<head>')) {
    // Remove existing <title>...</title>
    let cleaned = rawHtml.replace(/<title>[\s\S]*?<\/title>/gi, '');
    // Remove existing meta description/keywords/og tags if any to avoid duplication
    cleaned = cleaned.replace(/<meta\s+name=["']description["'][\s\S]*?>/gi, '');
    cleaned = cleaned.replace(/<meta\s+name=["']keywords["'][\s\S]*?>/gi, '');
    cleaned = cleaned.replace(/<meta\s+property=["']og:[\s\S]*?>/gi, '');
    cleaned = cleaned.replace(/<meta\s+name=["']twitter:[\s\S]*?>/gi, '');

    return cleaned.replace(/<head>/i, `<head>\n${tagsToInsert}`);
  }

  // If it doesn't have <html>/<head>, wrap in standard template
  return `<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
${tagsToInsert}
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>body { font-family: 'IBM Plex Sans Arabic', sans-serif; }</style>
</head>
<body class="bg-white text-slate-900 antialiased font-sans">
  ${rawHtml}
</body>
</html>`;
}

/**
 * Generates valid robots.txt for a published website
 */
export function generateRobotsTxt(projectUrl: string): string {
  const sitemapUrl = projectUrl.endsWith('/') ? `${projectUrl}sitemap.xml` : `${projectUrl}/sitemap.xml`;
  return `# robots.txt generated by Sawwiha Platform
User-agent: *
Allow: /

Sitemap: ${sitemapUrl}
`;
}

/**
 * Generates clean sitemap.xml for a published website
 */
export function generateSitemapXml(projectUrl: string, lastModified?: string): string {
  const cleanUrl = projectUrl.endsWith('/') ? projectUrl.slice(0, -1) : projectUrl;
  const isoDate = lastModified ? new Date(lastModified).toISOString().split('T')[0] : new Date().toISOString().split('T')[0];

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${cleanUrl}</loc>
    <lastmod>${isoDate}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
`;
}
